import type { Product } from "@/lib/api"

export const dummyProducts: Product[] = [
  {
    _id: "dummy-1",
    name: "Brass Puja Thali Set",
    slug: "brass-puja-thali-set",
    description: "Complete brass puja thali with all essential items for daily worship including diya, incense holder, bell, and kumkum container.",
    price: 899,
    originalPrice: 1299,
    category: "puja-items",
    primaryImage: { public_id: "dummy-1", url: "https://images.unsplash.com/photo-1771929712047-3e7022669175?w=600&h=600&fit=crop" },
    additionalImages: [],
    stockStatus: "in-stock",
    isEnergised: false,
    ratingsAverage: 4.5,
    ratingsCount: 128,
    sku: "PUJ-001",
  },
  {
    _id: "dummy-2",
    name: "Diya Lamp - Decorative",
    slug: "diya-lamp-decorative",
    description: "Beautiful decorative diya lamp with colorful floral arrangement, perfect for puja and festivals.",
    price: 450,
    originalPrice: 600,
    category: "puja-items",
    primaryImage: { public_id: "dummy-2", url: "https://images.unsplash.com/photo-1761328119419-154a21dcd64d?w=600&h=600&fit=crop" },
    additionalImages: [],
    stockStatus: "in-stock",
    isEnergised: false,
    ratingsAverage: 4.3,
    ratingsCount: 85,
    sku: "PUJ-002",
  },
  {
    _id: "dummy-3",
    name: "Ganesh Murti - Decorated",
    slug: "ganesh-murti-decorated",
    description: "Beautifully decorated Ganesh idol with offerings, perfect for home temple, Ganesh Chaturthi, and gifting.",
    price: 1500,
    originalPrice: 2000,
    category: "idols-murtis",
    primaryImage: { public_id: "dummy-3", url: "https://images.unsplash.com/photo-1759674881842-158e6edd73f8?w=600&h=600&fit=crop" },
    additionalImages: [],
    stockStatus: "in-stock",
    isEnergised: true,
    ratingsAverage: 4.8,
    ratingsCount: 256,
    sku: "IDO-001",
  },
  {
    _id: "dummy-4",
    name: "Sri Ram Lalla Idol",
    slug: "sri-ram-lalla-idol",
    description: "Ornate Sri Ram Lalla idol with intricate temple-style detailing, ideal for worship and home mandir.",
    price: 2200,
    category: "idols-murtis",
    primaryImage: { public_id: "dummy-4", url: "https://images.unsplash.com/photo-1759592370183-188810e5aea7?w=600&h=600&fit=crop" },
    additionalImages: [],
    stockStatus: "in-stock",
    isEnergised: true,
    ratingsAverage: 4.7,
    ratingsCount: 189,
    sku: "IDO-002",
  },
  {
    _id: "dummy-5",
    name: "Rudraksha Mala - 108 Beads",
    slug: "rudraksha-mala-108",
    description: "Authentic 5-mukhi Rudraksha mala with 108 beads, energised and lab-certified for meditation.",
    price: 800,
    originalPrice: 1100,
    category: "gemstones-malas",
    primaryImage: { public_id: "dummy-5", url: "https://images.unsplash.com/photo-1622993361118-b6365d859ab6?w=600&h=600&fit=crop" },
    additionalImages: [],
    stockStatus: "in-stock",
    isEnergised: true,
    ratingsAverage: 4.6,
    ratingsCount: 312,
    sku: "GEM-001",
  },
  {
    _id: "dummy-6",
    name: "Ganesh Idol - Purple",
    slug: "ganesh-idol-purple",
    description: "Stunning Lord Ganesha idol with vibrant purple backdrop, hand-painted and crafted for Ganesh Chaturthi.",
    price: 1800,
    category: "idols-murtis",
    primaryImage: { public_id: "dummy-6", url: "https://images.unsplash.com/photo-1732963916259-dd5c25829902?w=600&h=600&fit=crop" },
    additionalImages: [],
    stockStatus: "in-stock",
    isEnergised: true,
    ratingsAverage: 4.9,
    ratingsCount: 97,
    sku: "IDO-003",
  },
  {
    _id: "dummy-7",
    name: "Bhagavad Gita - Hindi",
    slug: "bhagavad-gita-hindi",
    description: "Complete Bhagavad Gita with Hindi translation and commentary by renowned scholars. Gold-embossed hardcover.",
    price: 350,
    originalPrice: 500,
    category: "books-scriptures",
    primaryImage: { public_id: "dummy-7", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL8s3CKZHRjhtRO8GgSHICGbORA4kkP9rBhQDcIwwchuba2V3Z5-xejVVvtNdzVXJTOwvRGODAyt9uGQtqmdruGpUAKgCjuHfS-2Bniw&s=10" },
    additionalImages: [],
    stockStatus: "in-stock",
    isEnergised: false,
    ratingsAverage: 4.9,
    ratingsCount: 445,
    sku: "BOO-001",
  },
  {
    _id: "dummy-8",
    name: "Hanuman Chalisa - Deluxe Edition",
    slug: "hanuman-chalisa-deluxe",
    description: "Beautifully illustrated Hanuman Chalisa with gold-embossed cover and meaning in English & Hindi.",
    price: 250,
    category: "books-scriptures",
    primaryImage: { public_id: "dummy-8", url: "https://m.media-amazon.com/images/I/71j9kEJ1Y7L._SY522_.jpg" },
    additionalImages: [],
    stockStatus: "in-stock",
    isEnergised: false,
    ratingsAverage: 4.7,
    ratingsCount: 203,
    sku: "BOO-002",
  },
]

export const dummyCategoryCounts: Record<string, number> = {
  "puja-items": 24,
  "idols-murtis": 18,
  "gemstones-malas": 15,
  "books-scriptures": 12,
}

export function getDummyProductsByCategory(category: string): Product[] {
  return dummyProducts.filter((p) => p.category === category)
}
